name: Test URLs in index.html

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  test-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Test URLs
        run: |
          # Replace 'index.html' with your file name if different
          urls=$(grep -oP 'href="\K[^"]+' index.html)  # Extract URLs from index.html

          for url in $urls; do
            if curl -o /dev/null --silent --head --fail "$url"; then
              echo "URL $url is reachable."
            else
              echo "URL $url is unreachable."
              exit 1
            fi
          done
